# -*- mode: ruby -*-
# vim: set ft=ruby :
GLOBAL_VMNAME = "otusraid"
GLOBAL_BOXNAME = "bento/oracle-8"
GLOBAL_DISK_PATH = "/otus2/vms/" + GLOBAL_VMNAME + "/"

Vagrant.configure("2") do |config|
    config.vm.box = GLOBAL_BOXNAME
    config.vm.hostname = GLOBAL_VMNAME
    config.vm.network "private_network", ip: "192.168.56.151"
    config.vm.define  GLOBAL_VMNAME
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.name = GLOBAL_VMNAME

        (1..5).each do |i|
            DISK = (GLOBAL_DISK_PATH + "sata#{i}.vdi")
            unless File.exist?(DISK)
                vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', "250"]
            end
            vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', i, '--device', 0, '--type', 'hdd', '--medium', DISK]
        end
        
    end
    config.vm.provision "shell", inline: <<-SHELL
        sudo mkdir -p ~root/.ssh;
        sudo cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo echo "PasswordAuthentication yes" > /etc/ssh/sshd_config
        sudo echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
        sudo echo "X11Forwarding no" >> /etc/ssh/sshd_config
        sudo echo "UsePAM yes" >> /etc/ssh/sshd_config
        sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        sudo echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
        sudo echo "AuthorizedKeysFile      .ssh/authorized_keys" >> /etc/ssh/sshd_config
        sudo echo "PermitEmptyPasswords no ">> /etc/ssh/sshd_config
        sudo echo "Subsystem	sftp	/usr/libexec/openssh/sftp-server ">> /etc/ssh/sshd_config
        sudo setenforce 0
        sudo systemctl stop firewalld.service
        sudo systemctl disable firewalld.service
        sudo dnf install python3 -y
        sudo dnf install mdadm smartmontools hdparm gdisk -y
        sudo dnf install mc -y
        sudo dnf install -y mdadm smartmontools hdparm gdisk
        sudo usermod -aG wheel vagrant
        sudo systemctl restart sshd
    SHELL
end