# -*- mode: ruby -*-
# vim: set ft=ruby :
GLOBAL_VMNAME = "rpm"
GLOBAL_BOXNAME = "bento/oracle-8"
GLOBAL_DISK_PATH = "/otus2/vms/" + GLOBAL_VMNAME + "/"
GLOBAL_BASECONF_SCRIPT = "scripts/baseconf.sh"
GLOBAL_CUSTOMCONF_SCRIPT = "scripts/custom.sh"

Vagrant.configure("2") do |config|
    config.vm.box = GLOBAL_BOXNAME
    config.vm.hostname = GLOBAL_VMNAME
    config.vm.network "private_network", ip: "192.168.56.157"
    config.vm.define  GLOBAL_VMNAME
    config.vm.box_check_update = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.name = GLOBAL_VMNAME
    end
    config.vm.provision "shell", path: GLOBAL_BASECONF_SCRIPT
    config.vm.provision "shell", path: GLOBAL_CUSTOMCONF_SCRIPT
end
