---

- name: Ping
  ping:

- name: Install Epel Rep
  yum:
   name: epel-release
   state: present

- name: Install Nginx
  yum:
   name: nginx
   state: latest
  notify:
   - restart nginx
  tags:
   - nginx-package
   - packages

- name: Copy config to Nginx
  template:
    dest: /etc/nginx/nginx.conf
    src:  ./nginx/templates/nginx.conf.j2
  notify:
   - reload nginx
  tags:
   - nginx-configuration