# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
        :box_name => "bento/oracle-8",
        :ip_addr => '192.168.56.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
            vb.customize ["modifyvm", :id,  "--cpus", "1"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            sudo mkdir -p ~root/.ssh;
            sudo cp ~vagrant/.ssh/auth* ~root/.ssh
            sudo echo "PasswordAuthentication yes" > /etc/ssh/sshd_config
            sudo echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
            sudo echo "X11Forwarding no" >> /etc/ssh/sshd_config
            sudo echo "UsePAM yes" >> /etc/ssh/sshd_config
            sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
            sudo echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
            sudo echo "AuthorizedKeysFile      .ssh/authorized_keys" >> /etc/ssh/sshd_config
            sudo echo "PermitEmptyPasswords no ">> /etc/ssh/sshd_config
            sudo echo "Subsystem	sftp	/usr/libexec/openssh/sftp-server ">> /etc/ssh/sshd_config
            sudo setenforce 0
            sudo systemctl stop firewalld.service
            sudo systemctl disable firewalld.service
#           sudo dnf install python3 -y
            sudo usermod -aG wheel vagrant
            sudo systemctl restart sshd
          SHELL
          
      end
  end
end
